- name: SonarCloud Scan
  uses: SonarSource/sonarqube-scan-action@v5.0.0
  env:
    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  with:
    args: >
      -Dsonar.projectKey=PACKAGE-EXPLORER_pyi40aas
      -Dsonar.organization=package-explorer
      -Dsonar.sources=.
